blank_issues_enabled: false
contact_links:
  - name: Upstream VoidAuth
    url: https://github.com/voidauth/voidauth
    about: For issues not related to the LDAP Sync feature, consider reporting upstream
  - name: Documentation
    url: https://github.com/mitchelljfranklin/mitch-auth/blob/mitch-voidauth/docs/Getting-Started.md
    about: Read the documentation before opening an issue
  - name: Quick Start
    url: https://github.com/mitchelljfranklin/mitch-auth#quick-start
    about: Get started with Mitch-Auth in minutes
